<?php

/**
 * @file
 * 
 */

/**
 * Implements field_attach_form().
 * 
 */
function multivalue_settings_field_attach_form($entity_type, $entity, &$form, &$form_state, $langcode) {
  dpm('in field_attach_form');
  //dpm('entity_type');
  //dpm($entity_type);
  dpm('entity');
  dpm($entity);
  dpm('form');
  dpm($form);
  dpm('form_state');
  dpm($form_state);
  
  // chceck if we are in an ajax callback
  if (isset($form_state['triggering_element'])) {
    $ajax = TRUE;
  } else $ajax = FALSE;
  
  // get the fields on this form
  $fields = $form_state['field'];
  //dpm('fields:');
  //dpm($fields);
  
  // iterate over the fields
  foreach ($fields as $field_name => $field) {
    // check whether they need to be altered by Multivalue Settings
    if (!isset($field[$langcode]['field']['settings']['multivalue_settings']) ||
        $field[$langcode]['field']['settings']['multivalue_settings']['enable'] == 0) {
          continue;
    }
    else $settings = $field[$langcode]['field']['settings']['multivalue_settings'];
    // field modifications
    //dpm('settings:');
    //dpm($settings);
    $allowed = $settings['allowed'];
    $required = $settings['required'];
    $initial = $settings['initial'];
    $extra = $settings['extra'];

    // set it up accordingly
    $element = &$form[$field_name][$langcode];

    dpm('element');
    dpm($element);
    /*
    unset($element[0]);
    unset($element[1]);
    unset($element[2]);
    dd($element);*/
    
    $element_num = $element['#max_delta'] + 1;
    //dpm("element has $element_num fields");
    
    
    if (!$ajax) {
      // find the number of values the field already has
      $value_num = $form_state['field'][$field_name][$langcode]['items_count'];
      // get the actual values
      if ($value_num > 0) {
        $values = $entity->$field_name;
        $values = $values[$langcode];
      }
      // find the number of extra empty fields we have
      $extra_num = $element_num - $value_num;
      // find the number of extra fields we want to have
      if ($extra == -1) {
        $extra = $allowed - $value_num;
      }
      // if there are no values in the field, we want to show $initial fields
      if ($value_num == 0) {
        // really $element_num in this case will always be 1
        if ($element_num < $initial) {
          $add = $initial - $element_num;
          multivalue_settings_add_items($element, $add, $field_name, $langcode, $form_state);
        }
      }
      elseif ($element_num > $allowed) {
        // we have to remove unallowed fields
        dpm('hi');
        $remove = $element_num - $allowed;
        dpm('remove');
        dpm($remove);
        multivalue_settings_remove_items($element, $remove, $field_name, $langcode, $form_state);
      } 
      elseif ($extra_num != $extra) {
        if ($extra_num > $extra) {
          // we have to remove unwanted extra fields
          $remove = $extra_num - $extra;
          multivalue_settings_remove_items($element, $remove, $field_name, $langcode, $form_state);
        }
        if ($extra > $extra_num) {
          // we have to add extra fields
          $add = $extra - $extra_num;
          multivalue_settings_add_items($element, $add, $field_name, $langcode, $form_state);
        }
      }
    } // end if ($ajax)
    // remove add more button if necessary
    $element_num = $element['#max_delta'] + 1;
    if ($element_num >= $allowed) {
      unset($element['add_more']);
    }
  }
}

function multivalue_settings_remove_items(&$element, $remove, $field_name, $langcode, &$form_state) {
  foreach (range(1, $remove) as $i) {
    multivalue_settings_remove_item($element, $field_name, $langcode, $form_state);
  }
}

function multivalue_settings_remove_item(&$element, $field_name, $langcode, &$form_state) {
  $max_delta = $element['#max_delta'];
  unset($element[$max_delta]);
  $delta  = $max_delta - 1;
  $element['#max_delta'] = $delta;
  $element['#prefix'] = '<div id="field-test-add-more-wrapper' . '--' . $delta . '">';
  $element['add_more']['#ajax']['wrapper'] = 'field-test-add-more-wrapper' . '--' . $delta ;
  $form_state['field'][$field_name][$langcode]['items_count'] = $delta;
}

function multivalue_settings_add_items(&$element, $add, $field_name, $langcode, &$form_state) {
  foreach (range(1, $add) as $i) {
    multivalue_settings_add_item($element, $field_name, $langcode, $form_state);
  }
}

function multivalue_settings_add_item(&$element, $field_name, $langcode, &$form_state) {
  $old_delta = $element['#max_delta'];
  $delta = $old_delta + 1; 
  // initialize new item
  $element[$delta] = $element[$old_delta];
  // incremenet item settings
  $element[$delta]['#delta'] = $delta;
  $element[$delta]['value']['#delta'] = $delta;
  $element[$delta]['#weight'] = $delta;
  $element[$delta]['value']['#weight'] = $delta;
  $element[$delta]['_weight']['#delta'] = $delta;
  $element[$delta]['_weight']['#default_value'] = $delta;
  // incremenet element settings
  $element['#max_delta'] = $delta;
  //$element['#prefix'] = '<div id="field-test-add-more-wrapper' . '--' . $i . '">';
  //$element['add_more']['#ajax']['wrapper'] = 'field-test-add-more-wrapper' . '--' . $i;
  // update the item count. Necessary for add_more ajax to work
  $form_state['field'][$field_name][$langcode]['items_count'] = $delta;
  
}

function multivalue_settings_increment_element($element, $delta) {
  $element['#delta'] = $delta;
  $element['value']['#delta'] = $delta;
  $element['#weight'] = $delta;
  $element['value']['#weight'] = $delta;
  $element['_weight']['#delta'] = $delta;
  $element['_weight']['#default_value'] = $delta;
  return $element;
}

 /**
  * Implements hook_form_FORM_ID_alter().
  * Adds the settings to the Field Settings form
  */
function multivalue_settings_form_field_ui_field_edit_form_alter(&$form, $form_state, $form_id) {
  // change the regular multiple values form element to an internal value
  unset($form['field']['cardinality']);
  $form['field']['cardinality'] = array(
    '#type'   => 'value',
    '#value'  => NULL,
  );
  
  // add a validate handler for this form
  $form['#validate'][] = 'multivalue_settings_validate_settings';
  
  // create the new settings form elements
  $allowed_max = 100;
  $initial_max = 30;
  $extra_max = 10;
  $allowed = $allowed_max;
  /* check if there is already a number of allowed values in form_state (which
   * means this is running from an AJAX call) or otherwise, if there is a value
   * that has been previously selected in this form */
  if (!empty($form_state['values']['field']['settings']['multivalue_settings']['allowed'])) {
    $allowed = $form_state['values']['field']['settings']['multivalue_settings']['allowed'];
  }
  elseif (!empty($form['#field']['settings']['multivalue_settings']['allowed'])) {
    $allowed = $form['#field']['settings']['multivalue_settings']['allowed'];
  }
  
  // get default values
  $values = $form['#field']['settings']['multivalue_settings'];
  
  // the fieldset
  $form['field']['settings']['multivalue_settings'] = array(
    '#type'   => 'fieldset',
    '#title'  => 'Multivalue Settings',
  );
  
  // the checkbox to enable these settings and show the field
  $form['field']['settings']['multivalue_settings']['enable'] = array(
    '#type'   => 'checkbox',
    '#title'  => t('This field can contain more than one value'),
    '#default_value'  => $values['enable'],
  );
  
  // number of allowed values
  $options = array(FIELD_CARDINALITY_UNLIMITED => t('Unlimited')) + drupal_map_assoc(range(2, $allowed_max));
  $form['field']['settings']['multivalue_settings']['allowed'] = array(
    '#type'       => 'select',
    '#title'      => t('Number of values allowed'),
    '#default_value'  => $values['allowed'],
    '#description'    => t('This is the maximum number of values this field may have'),
    '#options'    => $options,
    '#ajax'       => array(
      'callback'  => 'multivalue_settings_required_callback',
      'wrapper'   => 'multivalue-settings-wrapper',
    ),
    '#states' => array(
      'visible' => array(
        ':input[name="field[settings][multivalue_settings][enable]"]' => array('checked' => TRUE),
      ),
    ),
  );
  
  // number of required values
  $options = array('0' => t('None'));
  if ($allowed != -1) $options += drupal_map_assoc(range(1, $allowed));
  else $options += drupal_map_assoc(range(1, $allowed_max));
  $form['field']['settings']['multivalue_settings']['required'] = array(
    '#type'       => 'select',
    '#title'      => t('Number of values required'),
    '#default_value'  => $values['required'],
    '#description'    => t('This is the minimum number of values this field is required to have'),
    '#options'    => $options,
    '#prefix'     => '<div id="multivalue-settings-wrapper">',
    '#states' => array(
      'visible' => array(
        ':input[name="field[settings][multivalue_settings][enable]"]' => array('checked' => TRUE),
      ),
    ),
  );
  
  // number of values to show initially
  if ($allowed != -1) $options = drupal_map_assoc(range(1, min($allowed, $initial_max)));
  else $options = drupal_map_assoc(range(1, $initial_max));
  $form['field']['settings']['multivalue_settings']['initial'] = array(
    '#type'       => 'select',
    '#title'      => t('Number of initial fields'),
    '#default_value'  => $values['initial'],
    '#description'    => t('This is the number of field instances to show if no values are saved to this field yet'),
    '#options'    => $options,
    '#states' => array(
      'visible' => array(
        ':input[name="field[settings][multivalue_settings][enable]"]' => array('checked' => TRUE),
      ),
    ),
  );
  
  // number of extra empty fields to show on edit
  $options = array('0' => t('None'));
  if ($allowed != -1) {
    $options += array('-1' => t('Show full number of allowed fields'));
    $options += drupal_map_assoc(range(1, min($allowed - 1, $extra_max)));
  }
  else $options += drupal_map_assoc(range(1, $extra_max));
  $form['field']['settings']['multivalue_settings']['extra'] = array(
    '#type'       => 'select',
    '#title'      => t('Number of extra empty fields'),
    '#default_value'  => $values['extra'],
    '#description'    => t('This is the maximum number of extra empty field instances to show when the field already has some values'),
    '#options'    => $options,
    '#suffix'     => '</div>',
    '#states' => array(
      'visible' => array(
        ':input[name="field[settings][multivalue_settings][enable]"]' => array('checked' => TRUE),
      ),
    ),
  ); 
}

/**
 * 
 * 
 */
function multivalue_settings_required_callback($form, &$form_state) {
  $return = array('required' => $form['field']['settings']['multivalue_settings']['required'],
                  'initial' => $form['field']['settings']['multivalue_settings']['initial'],
                  'extra' => $form['field']['settings']['multivalue_settings']['extra'],
            );
  //dpm($return);
  return $return;
}

/**
 * 
 * 
 */
function multivalue_settings_validate_settings($form, &$form_state) {
  //dpm('in submit function for settings');
  //dpm($form_state['input']);
  //dpm($form_state['values']);
  // fix cardinality
  $settings = $form_state['values']['field']['settings']['multivalue_settings'];
  if ($settings['enable'] == 0) {
    $form_state['values']['field']['cardinality'] = 1;
  }
  else {
    // set cardinality always to 'Unlimited' so that we get the add more button
    $form_state['values']['field']['cardinality'] = FIELD_CARDINALITY_UNLIMITED;
  }
}